#!/bin/bash

# SERVICES
cat services/geminiService.ts > /dev/null 2>&1
cat services/offlineService.ts > /dev/null 2>&1
cat services/loggingService.ts > /dev/null 2>&1
cat services/EconomicService.ts > /dev/null 2>&1
cat services/archiveService.ts > /dev/null 2>&1
cat services/LegalAIAgent.ts > /dev/null 2>&1
cat services/logger.ts > /dev/null 2>&1
cat services/usageMonitorService.ts > /dev/null 2>&1
cat services/githubService.ts > /dev/null 2>&1

# LIB CORE
cat lib/db.ts > /dev/null 2>&1
cat lib/ragService.ts > /dev/null 2>&1
cat lib/AIOrchestrator.ts > /dev/null 2>&1
cat lib/executionFlow.ts > /dev/null 2>&1
cat lib/CaseManagementService.ts > /dev/null 2>&1
cat lib/LegalPipelineService.ts > /dev/null 2>&1
cat lib/cis.types.ts > /dev/null 2>&1
cat lib/economic.types.ts > /dev/null 2>&1
cat lib/verification.ts > /dev/null 2>&1
cat lib/CorpusService.ts > /dev/null 2>&1
cat lib/syntheticLLMResponses.ts > /dev/null 2>&1
cat lib/AuditService.ts > /dev/null 2>&1
cat lib/JournalService.ts > /dev/null 2>&1
cat lib/AutoNotaryService.ts > /dev/null 2>&1
cat lib/GlobalSessionManager.ts > /dev/null 2>&1
cat lib/AIAnalysisEngine.ts > /dev/null 2>&1
cat lib/AIFactEngine.ts > /dev/null 2>&1
cat lib/AILinkingEngine.ts > /dev/null 2>&1
cat lib/ForensicChainService.ts > /dev/null 2>&1
cat lib/IntegrityEngine.ts > /dev/null 2>&1
cat lib/hashHelper.ts > /dev/null 2>&1
cat lib/hashUtils.ts > /dev/null 2>&1
cat lib/LegalReasoningService.ts > /dev/null 2>&1
cat lib/DecisionSupportService.ts > /dev/null 2>&1
cat lib/RagIndexService.ts > /dev/null 2>&1
cat lib/QueryProvenanceService.ts > /dev/null 2>&1
cat lib/opinionEngine.ts > /dev/null 2>&1
cat lib/LegalTextProductionEngine.ts > /dev/null 2>&1
cat lib/adversarialEngine.ts > /dev/null 2>&1
cat lib/riskEngineV6.ts > /dev/null 2>&1
cat lib/riskEngineV6.types.ts > /dev/null 2>&1
cat lib/SfbValidationService.ts > /dev/null 2>&1
cat lib/ConsolidationService.ts > /dev/null 2>&1
cat lib/normalizationEngine.ts > /dev/null 2>&1
cat lib/legalReferenceEngine.ts > /dev/null 2>&1
cat lib/legalMapper.ts > /dev/null 2>&1
cat lib/LegalMappingService.ts > /dev/null 2>&1
cat lib/factEngine.ts > /dev/null 2>&1
cat lib/keywordEngine.ts > /dev/null 2>&1
cat lib/triggerEngine.ts > /dev/null 2>&1
cat lib/validationModule.ts > /dev/null 2>&1
cat lib/reportGenerator.ts > /dev/null 2>&1
cat lib/generateLegalReport.ts > /dev/null 2>&1
cat lib/BaseService.ts > /dev/null 2>&1
cat lib/ErrorHandler.ts > /dev/null 2>&1
cat lib/errors.ts > /dev/null 2>&1

# DATA FILES
cat data/legalFramework.ts > /dev/null 2>&1
cat data/legalCorpus.ts > /dev/null 2>&1
cat data/caseTypeRegistry.ts > /dev/null 2>&1
cat data/opinionTemplates.ts > /dev/null 2>&1
cat data/riskDefinitions.ts > /dev/null 2>&1
cat data/groundTruth.ts > /dev/null 2>&1
cat data/syntheticAnalysisResult.ts > /dev/null 2>&1
cat data/legalFrameworkContent.ts > /dev/null 2>&1
cat data/legalSources.ts > /dev/null 2>&1
cat data/contextWeights.ts > /dev/null 2>&1
cat data/externalSources.ts > /dev/null 2>&1
cat data/riskTemplateRegistry.ts > /dev/null 2>&1

# COMPONENTS
cat App.tsx > /dev/null 2>&1
cat components/SystemHub.tsx > /dev/null 2>&1
cat components/ArchiveView.tsx > /dev/null 2>&1
cat components/AnalysisView.tsx > /dev/null 2>&1
cat components/AnalysisResults.tsx > /dev/null 2>&1
cat components/InteractiveAnalyst.tsx > /dev/null 2>&1
cat components/EconomicDashboard.tsx > /dev/null 2>&1
cat components/LegalPipelineView.tsx > /dev/null 2>&1
cat components/AgentView.tsx > /dev/null 2>&1
cat components/AgentWorkspace.tsx > /dev/null 2>&1
cat components/ForensicIntegrityView.tsx > /dev/null 2>&1
cat components/AuditPanel.tsx > /dev/null 2>&1
cat components/AutoNotaryView.tsx > /dev/null 2>&1
cat components/SfbIntegrityPanel.tsx > /dev/null 2>&1
cat components/LegalFrameworkView.tsx > /dev/null 2>&1
cat components/WhitebookViewer.tsx > /dev/null 2>&1
cat components/OracleCoreViewer.tsx > /dev/null 2>&1
cat components/SystemMonitor.tsx > /dev/null 2>&1
cat components/SystemInventory.tsx > /dev/null 2>&1
cat components/ControllerDashboard.tsx > /dev/null 2>&1
cat components/DocumentManager.tsx > /dev/null 2>&1
cat components/FileUpload.tsx > /dev/null 2>&1
cat components/OpinionGenerator.tsx > /dev/null 2>&1
cat components/AdversarialDuelView.tsx > /dev/null 2>&1
cat components/CaseProfiler.tsx > /dev/null 2>&1
cat components/LegalTextProductionModule.tsx > /dev/null 2>&1
cat components/DecisionSupportViewer.tsx > /dev/null 2>&1
cat components/LegalReasoningViewer.tsx > /dev/null 2>&1
cat components/ReportViewer.tsx > /dev/null 2>&1
cat components/ForensicAuditView.tsx > /dev/null 2>&1
cat components/AnalysisDashboard.tsx > /dev/null 2>&1
cat components/CaseViewer.tsx > /dev/null 2>&1
cat components/ConsolidationViewer.tsx > /dev/null 2>&1
cat components/RiskConflictViewer.tsx > /dev/null 2>&1
cat components/ProportionalityViewer.tsx > /dev/null 2>&1
cat components/ActionRecommendationViewer.tsx > /dev/null 2>&1
cat components/PipelineStatus.tsx > /dev/null 2>&1
cat components/SystemHealthDashboard.tsx > /dev/null 2>&1
cat components/SystemOverview.tsx > /dev/null 2>&1
cat components/SystemArchitectureView.tsx > /dev/null 2>&1
cat components/StaticArchitectureView.tsx > /dev/null 2>&1
cat components/SystemDocumentation.tsx > /dev/null 2>&1
cat components/SystemGuide.tsx > /dev/null 2>&1
cat components/MasterDashboard.tsx > /dev/null 2>&1
cat components/FmjamController.tsx > /dev/null 2>&1
cat components/IntelligenceCore.tsx > /dev/null 2>&1
cat components/ControlPanel.tsx > /dev/null 2>&1
cat components/CaseTimeline.tsx > /dev/null 2>&1
cat components/TimelineView.tsx > /dev/null 2>&1
cat components/AIDebugPanel.tsx > /dev/null 2>&1
cat components/ErrorDashboard.tsx > /dev/null 2>&1
cat components/ArchiveCoreViewer.tsx > /dev/null 2>&1
cat components/ArchiveSearch.tsx > /dev/null 2>&1
cat components/QuickStartGuide.tsx > /dev/null 2>&1
cat components/QuotaWarning.tsx > /dev/null 2>&1
cat components/LoginScreen.tsx > /dev/null 2>&1
cat components/AppErrorBoundary.tsx > /dev/null 2>&1
cat components/OfflineBanner.tsx > /dev/null 2>&1
cat components/icons.tsx > /dev/null 2>&1
cat components/shared/Card.tsx > /dev/null 2>&1
cat components/shared/MarkdownRenderer.tsx > /dev/null 2>&1
cat components/shared/Tabs.tsx > /dev/null 2>&1
cat components/shared/Toast.tsx > /dev/null 2>&1
cat components/shared/RiskProfileEditor.tsx > /dev/null 2>&1
cat components/TextInput.tsx > /dev/null 2>&1
cat components/Chatbot.tsx > /dev/null 2>&1

# CONFIG
cat types.ts > /dev/null 2>&1
cat index.tsx > /dev/null 2>&1
cat bootstrap.tsx > /dev/null 2>&1
cat vite.config.ts > /dev/null 2>&1
cat tsconfig.json > /dev/null 2>&1
cat package.json > /dev/null 2>&1
cat index.css > /dev/null 2>&1

echo "Reading complete."
